# Generated by Django 5.2 on 2025-04-13 05:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moves', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In_Progess'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(verbose_name=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
