# Generated by Django 5.2 on 2025-05-10 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_alter_game_game_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='player_2_status',
            field=models.CharField(choices=[('player_2_not_joined', 'Player_2_Not_Joined'), ('player_2_joined', 'Player_2_Joined')], default='player_2_not_joined', max_length=30),
        ),
    ]
