# Generated by Django 5.2.4 on 2025-07-17 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_game_player_2_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='status',
            new_name='game_status',
        ),
        migrations.AddField(
            model_name='game',
            name='game_draw',
            field=models.BooleanField(default=False),
        ),
    ]
